### ISSUE TITLE
移植为Firefox等其他浏览器的插件

### ISSUE THREAD

**Issue by songzhi** [coder-ysj/jike-web-qr#1]
如果开发者没有时间,可以考虑把浏览器耦合的代码提取出来或添加注释文档等便于大家贡献代码

**Comment by viko16** [comment]
没问题，近期解决。
但是上架可能有点麻烦 😂

**Comment by coder-ysj** [comment]
谢谢你的反馈！

目前 Jike Web QR 正在进行较大的变动，为接下来的 1.0.0 正式版铺路，所以跨浏览器方案暂时搁浅。

如果没有足够的时间去完成跨浏览器版本开发的话，我会在源代码中补充详细的注释，供大家自行移植。
